export const EVENTS = [
  {
    id: 1,
    emoji: '⚽',
    title: 'Sunday Morning Football',
    description: 'Casual pickup football game at Fleetwood Park. All skill levels welcome! We meet every Sunday and split into teams on the spot. Bring water and wear cleats if you have them.',
    category: 'Sports',
    date: 'Sun Apr 6, 10:00 AM',
    location: 'Fleetwood Park, Surrey',
    languages: ['ES', 'EN'],
    capacity: 16,
    spots: 4,
    color: '#6A9E72',
    host: 'Carlos M.',
    hostHue: 120,
    attendees: [200, 30, 80],
  },
  {
    id: 2,
    emoji: '🍜',
    title: 'Dumpling-Making Workshop',
    description: "Learn to fold authentic jiaozi dumplings from scratch. Ingredients provided. We'll make pork & cabbage and vegetarian fillings. Everyone goes home with a recipe card.",
    category: 'Culture',
    date: 'Sat Apr 5, 2:00 PM',
    location: 'Whalley Community Hall',
    languages: ['ZH', 'EN'],
    capacity: 12,
    spots: 3,
    color: '#5B9DC9',
    host: 'Mei L.',
    hostHue: 200,
    attendees: [10, 40, 300],
  },
  {
    id: 3,
    emoji: '🎭',
    title: 'Newcomers Storytelling Night',
    description: 'A safe, welcoming space to share your immigration story — the funny moments, the hard ones, and everything in between. No performance experience needed.',
    category: 'Meetup',
    date: 'Fri Apr 11, 6:30 PM',
    location: 'Newton Library Meeting Room',
    languages: ['EN', 'FR', 'AR'],
    capacity: 20,
    spots: 11,
    color: '#D4A034',
    host: 'Fatima B.',
    hostHue: 45,
    attendees: [170, 55, 290],
  },
  {
    id: 4,
    emoji: '🏀',
    title: 'Basketball Pickup — Thursdays',
    description: '3-on-3 pickup basketball every Thursday evening at the outdoor court. Rotating teams, friendly vibe. Bring your own ball if you can, extras available.',
    category: 'Sports',
    date: 'Thu Apr 10, 7:00 PM',
    location: 'Bear Creek Park Courts',
    languages: ['EN', 'TA'],
    capacity: 12,
    spots: 2,
    color: '#E8846A',
    host: 'Priya K.',
    hostHue: 340,
    attendees: [60, 180, 310],
  },
  {
    id: 5,
    emoji: '🧘',
    title: 'Morning Yoga in the Park',
    description: 'Start your weekend right with a free outdoor yoga session. Suitable for all levels. Bring a mat or blanket. Sessions are bilingual (Farsi/English).',
    category: 'Wellness',
    date: 'Sat Apr 5, 8:00 AM',
    location: 'Holland Park, Surrey',
    languages: ['FA', 'EN'],
    capacity: 15,
    spots: 6,
    color: '#A78BCA',
    host: 'Shirin N.',
    hostHue: 270,
    attendees: [75, 140, 210],
  },
  {
    id: 6,
    emoji: '🎨',
    title: 'Henna Art & Tea Afternoon',
    description: 'Come enjoy henna art, Moroccan mint tea, and great conversation. Open to everyone curious about North African culture. Henna artist will be on hand.',
    category: 'Culture',
    date: 'Sun Apr 13, 3:00 PM',
    location: 'Guildford Town Centre Community Room',
    languages: ['AR', 'FR', 'EN'],
    capacity: 18,
    spots: 9,
    color: '#C97B4B',
    host: 'Layla H.',
    hostHue: 25,
    attendees: [90, 220, 350],
  },
];

export const SERVICES = [
  {
    id: 1,
    title: 'Professional Haircuts & Fades',
    provider: 'Amara D.',
    desc: 'Experienced barber offering precision cuts, fades, and beard trims from home studio in Whalley. 5+ years of experience with all hair textures.',
    category: 'Beauty',
    languages: ['AM', 'EN'],
    price: '$25 / session',
    rating: '4.9',
    since: '2023',
    hue: 30,
    reviews: [
      { name: 'Dawit T.', stars: 5, hue: 180, text: "Best fade I've had since moving to Canada. Amara really knows his craft." },
      { name: 'Yosef M.', stars: 5, hue: 240, text: 'Affordable and super clean. Books up fast so message early!' },
    ],
  },
  {
    id: 2,
    title: 'Math & Physics Tutoring (K–12)',
    provider: 'Reza P.',
    desc: 'Former university instructor from Tehran now helping students in Surrey ace their math and physics. Patient, structured, and results-driven.',
    category: 'Education',
    languages: ['FA', 'EN'],
    price: '$40 / hr',
    rating: '4.8',
    since: '2022',
    hue: 200,
    reviews: [
      { name: 'Sara K.', stars: 5, hue: 290, text: 'My daughter went from a C to an A in two months. Reza explains everything so clearly.' },
      { name: 'Niloufar H.', stars: 4, hue: 60, text: 'Very knowledgeable. Flexible with scheduling too.' },
    ],
  },
  {
    id: 3,
    title: 'Immigration Document Consultation',
    provider: 'Grace O.',
    desc: 'Certified immigration consultant helping newcomers navigate PR applications, study permits, and citizenship documents. Bilingual consultations available.',
    category: 'Legal',
    languages: ['YO', 'EN', 'FR'],
    price: '$60 / hr',
    rating: '5.0',
    since: '2021',
    hue: 140,
    reviews: [
      { name: 'Adebayo F.', stars: 5, hue: 20, text: 'Grace saved me so much stress during my PR application. Highly recommend.' },
      { name: 'Chinwe N.', stars: 5, hue: 160, text: 'Very thorough and professional. She caught errors I would have missed.' },
    ],
  },
  {
    id: 4,
    title: 'Homemade Halal Meal Prep',
    provider: 'Nadia B.',
    desc: 'Weekly halal meal prep delivered within Surrey. Moroccan, Lebanese, and fusion options. Customizable for dietary needs. Order by Wednesday for Friday delivery.',
    category: 'Food',
    languages: ['AR', 'FR', 'EN'],
    price: 'From $55 / week',
    rating: '4.7',
    since: '2023',
    hue: 350,
    reviews: [
      { name: 'Khalid M.', stars: 5, hue: 100, text: 'Finally feel at home food-wise. The tagine is incredible.' },
      { name: 'Leila R.', stars: 4, hue: 210, text: 'Portions are generous and everything is fresh. Will reorder.' },
    ],
  },
  {
    id: 5,
    title: 'English Conversation Practice',
    provider: 'Ji-woo C.',
    desc: 'Relaxed 1-on-1 or small group English practice sessions focused on everyday conversation, pronunciation, and confidence. No textbooks — just real talk.',
    category: 'Education',
    languages: ['KO', 'EN'],
    price: '$20 / hr',
    rating: '4.9',
    since: '2022',
    hue: 220,
    reviews: [
      { name: 'Min-jun L.', stars: 5, hue: 80, text: 'Ji-woo made me feel so comfortable speaking English. Great listener.' },
      { name: 'Hyun S.', stars: 5, hue: 330, text: 'My confidence improved so much after just a few sessions.' },
    ],
  },
  {
    id: 6,
    title: 'Car Maintenance & Minor Repairs',
    provider: 'Santos V.',
    desc: 'Certified mechanic offering affordable oil changes, brake inspections, and minor repairs. Mobile service — I come to you. Honest pricing, no surprise fees.',
    category: 'Trades',
    languages: ['ES', 'EN'],
    price: 'From $40',
    rating: '4.8',
    since: '2022',
    hue: 165,
    reviews: [
      { name: 'Maria G.', stars: 5, hue: 45, text: 'So convenient. Santos came to my apartment parking lot. Saved me hours.' },
      { name: 'Roberto C.', stars: 5, hue: 270, text: 'Fair prices and he explains everything clearly. My go-to mechanic.' },
    ],
  },
];

export const EVENT_CATEGORIES = ['Sports', 'Culture', 'Meetup', 'Wellness'];
export const SERVICE_CATEGORIES = ['Beauty', 'Education', 'Legal', 'Food', 'Trades'];
